src/MyMvcNetCore.Web/Areas/Admin/Controllers/DashboardController.cs
using EShop.Web.Areas.Admin;
using Microsoft.AspNetCore.Mvc;
using MyMvcNetCore.Web.Models;
using System.Diagnostics;

namespace MyMvcNetCore.Web.Areas.Admin.Controllers
{
    [Area(AreaConstants.AdminArea)]
public class DashboardController : BaseController
{
        private readonly ILogger<DashboardController> _logger;

        public DashboardController(ILogger<DashboardController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

src/MyMvcNetCore.Web/ViewComponents/AllCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyMvcNetCore.DataLayer.Context;
using MyMvcNetCore.DataLayer.Repository.IRepository;
using MyMvcNetCore.Entities;
using MyMvcNetCore.Services.EFContracts;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyMvcNetCore.Web.ViewComponents
{
    public class AllCategoryViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _uow;
        private readonly ICategoryService _categoryService;
        public AllCategoryViewComponent(ICategoryService categoryService, IUnitOfWork uow)
        {
           _categoryService = categoryService;
            _uow = uow;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryService.AllMainCategoriesAsync();
            return View(categories);
        }
     
    }
}

src/MyMvcNetCore.Web/ViewComponents/NewsletterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyMvcNetCore.DataLayer.Context;
using MyMvcNetCore.DataLayer.Repository.IRepository;
using MyMvcNetCore.Entities;
using MyMvcNetCore.Services.EFContracts;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyMvcNetCore.Web.ViewComponents
{
    public class NewsletterViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _uow;
        private readonly ICategoryService _categoryService;
        public NewsletterViewComponent(ICategoryService categoryService, IUnitOfWork uow)
        {
            _categoryService = categoryService;
            _uow = uow;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }

    }
}

src/MyMvcNetCore.Web/ViewComponents/SearchProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyMvcNetCore.DataLayer.Context;
using MyMvcNetCore.DataLayer.Repository.IRepository;
using MyMvcNetCore.Entities;
using MyMvcNetCore.Services.EFContracts;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyMvcNetCore.Web.ViewComponents
{
    public class SearchProductViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _uow;
        private readonly ICategoryService _categoryService;
        public SearchProductViewComponent(ICategoryService categoryService, IUnitOfWork uow)
        {
           _categoryService = categoryService;
            _uow = uow;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryService.AllMainCategoriesAsync();
            return View(categories);
        }
     
    }
}

src/MyMvcNetCore.Web/Views/Shared/_AllCategoryPartial.cshtml
<div class="all-category">
    <h3 class="cat-heading"><i class="fa fa-bars" aria-hidden="true"></i>CATEGORIES</h3>
    <ul class="main-category">
        <li>
            <a href="#">New Arrivals <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <ul class="sub-category">
                <li><a href="#">accessories</a></li>
                <li><a href="#">best selling</a></li>
                <li><a href="#">top 100 offer</a></li>
                <li><a href="#">sunglass</a></li>
                <li><a href="#">watch</a></li>
                <li><a href="#">man’s product</a></li>
                <li><a href="#">ladies</a></li>
                <li><a href="#">westrn dress</a></li>
                <li><a href="#">denim </a></li>
            </ul>
        </li>
        <li class="main-mega">
            <a href="#">best selling <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <ul class="mega-menu">
                <li class="single-menu">
                    <a href="#" class="title-link">Shop Kid's</a>
                    <div class="image">
                        <img src="https://via.placeholder.com/225x155" alt="#">
                    </div>
                    <div class="inner-link">
                        <a href="#">Kids Toys</a>
                        <a href="#">Kids Travel Car</a>
                        <a href="#">Kids Color Shape</a>
                        <a href="#">Kids Tent</a>
                    </div>
                </li>
                <li class="single-menu">
                    <a href="#" class="title-link">Shop Men's</a>
                    <div class="image">
                        <img src="https://via.placeholder.com/225x155" alt="#">
                    </div>
                    <div class="inner-link">
                        <a href="#">Watch</a>
                        <a href="#">T-shirt</a>
                        <a href="#">Hoodies</a>
                        <a href="#">Formal Pant</a>
                    </div>
                </li>
                <li class="single-menu">
                    <a href="#" class="title-link">Shop Women's</a>
                    <div class="image">
                        <img src="https://via.placeholder.com/225x155" alt="#">
                    </div>
                    <div class="inner-link">
                        <a href="#">Ladies Shirt</a>
                        <a href="#">Ladies Frog</a>
                        <a href="#">Ladies Sun Glass</a>
                        <a href="#">Ladies Watch</a>
                    </div>
                </li>
            </ul>
        </li>
        <li><a href="#">accessories</a></li>
        <li><a href="#">top 100 offer</a></li>
        <li><a href="#">sunglass</a></li>
        <li><a href="#">watch</a></li>
        <li><a href="#">man’s product</a></li>
        <li><a href="#">ladies</a></li>
        <li><a href="#">westrn dress</a></li>
        <li><a href="#">denim </a></li>
    </ul>
</div>

src/MyMvcNetCore.Web/Views/Shared/_FooterPartial.cshtml
<footer class="footer">
	<!-- Footer Top -->
	<div class="footer-top section">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-6 col-12">
					<!-- Single Widget -->
					<div class="single-footer about">
						<div class="logo">
							<a href="index.html"><img src="images/logo2.png" alt="#"></a>
						</div>
						<p class="text">
                            Fast, secure, and reliable online shopping. Enjoy seamless checkout, trusted products, and friendly support whenever you need it. Shop smart, shop easy.
                            
						</p>
						<p class="call">
                            Got questions? Call us 24/7<span>
								<a href="tel:123456789">
                                    +49 801
								</a>
							</span>
						</p>
					</div>
					<!-- End Single Widget -->
				</div>
				<div class="col-lg-2 col-md-6 col-12">
					<!-- Single Widget -->
					<div class="single-footer links">
						<h4>Information</h4>
						<ul>
							<li><a href="#">About Us</a></li>
							<li><a href="#">Faq</a></li>
							<li><a href="#">Terms & Conditions</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Help</a></li>
						</ul>
					</div>
					<!-- End Single Widget -->
				</div>
				<div class="col-lg-2 col-md-6 col-12">
					<!-- Single Widget -->
					<div class="single-footer links">
						<h4>Customer Service</h4>
						<ul>
							<li><a href="#">Payment Methods</a></li>
							<li><a href="#">Money-back</a></li>
							<li><a href="#">Returns</a></li>
							<li><a href="#">Shipping</a></li>
							<li><a href="#">Privacy Policy</a></li>
						</ul>
					</div>
					<!-- End Single Widget -->
				</div>
				<div class="col-lg-3 col-md-6 col-12">
					<!-- Single Widget -->
					<div class="single-footer social">
						<h4>Get In Tuch</h4>
						<!-- Single Widget -->
						<div class="contact">
							<ul>
								<li>Address</li>
								<li>Country</li>
								<li>info@eshop.com</li>
								<li>+49 1111 1111</li>
							</ul>
						</div>
						<!-- End Single Widget -->
						<ul>
							<li><a href="#"><i class="ti-facebook"></i></a></li>
							<li><a href="#"><i class="ti-twitter"></i></a></li>
							<li><a href="#"><i class="ti-flickr"></i></a></li>
							<li><a href="#"><i class="ti-instagram"></i></a></li>
						</ul>
					</div>
					<!-- End Single Widget -->
				</div>
			</div>
		</div>
	</div>
	<!-- End Footer Top -->
	<div class="copyright">
		<div class="container">
			<div class="inner">
				<div class="row">
					<div class="col-lg-6 col-12">
						<div class="left">
							<p>
								Copyright © 2025 <a href="#"
							target="_blank">Ehsan Company</a> - All Rights Reserved.
							</p>
						</div>
					</div>
					<div class="col-lg-6 col-12">
						<div class="right">
							<img src="images/payments.png" alt="#">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

src/MyMvcNetCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> - Ehsan.SHOP - @ViewData["Title"]-</title>


    <!-- Favicon -->
    <link rel="icon" type="image/png" href="~/images/layout_General/favicon.png">
    <!-- Web Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <!-- StyleSheet -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/css/layout_General/bootstrap.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/css/layout_General/magnific-popup.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/css/layout_General/font-awesome.css">
    <!-- Fancybox -->
    <link rel="stylesheet" href="~/css/layout_General/jquery.fancybox.min.css">
    <!-- Themify Icons -->
    <link rel="stylesheet" href="~/css/layout_General/themify-icons.css">
    <!-- Nice Select CSS -->
    <link rel="stylesheet" href="~/css/layout_General/niceselect.css">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="~/css/layout_General/animate.css">
    <!-- Flex Slider CSS -->
    <link rel="stylesheet" href="~/css/layout_General/flex-slider.min.css">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/css/layout_General/owl-carousel.css">
    <!-- Slicknav -->
    <link rel="stylesheet" href="~/css/layout_General/slicknav.min.css">

    <!-- Eshop StyleSheet -->
    <link rel="stylesheet" href="~/css/layout_General/reset.css">
    <link rel="stylesheet" href="~/css/layout_General/style.css">
    <link rel="stylesheet" href="~/css/layout_General/responsive.css">



</head>
<body class="js">
    <!-- Preloader -->
    <div class="preloader">
        <div class="preloader-inner">
            <div class="preloader-icon">
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- End Preloader -->
    <!-- Header -->
    <header class="header shop">
        <!-- Topbar -->
        <partial name="_TopbarPartial"></partial>
        <!-- End Topbar -->
        <!-- Middle Inner -->
        <partial name="_MiddleInnerPartial"></partial>
        <!-- End Middle Inner -->
        <!-- Header Inner -->
        <div class="header-inner">
            <div class="container">
                <div class="cat-nav-head">
                    <div class="row">
                        <div class="col-lg-3">
                            @await Component.InvokeAsync("AllCategory")
                        </div>
                        <div class="col-lg-9 col-12">
                            <partial name="_MenuAreaPartial"></partial>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ End Header Inner -->
    </header>
    <!--/ End Header -->
    <!-- Slider Area -->
    <section class="hero-slider">
        <!-- Single Slider -->
        <div class="single-slider">
            <div class="container">
                <div class="row no-gutters">
                    <div class="col-lg-9 offset-lg-3 col-12">
                        <div class="text-inner">
                            <div class="row">
                                <div class="col-lg-7 col-12">
                                    <div class="hero-text">
                                        <h1><span>UP TO 50% OFF </span>Shirt For Man</h1>
                                        <p>Elevate your style with our men's shirts.Designed for<br> both comfort and elegance, our collection features<br> modern cuts and premium fabrics</p>

                                     
                                        <div class="button">
                                            <a href="#" class="btn">Shop Now!</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ End Single Slider -->
    </section>
    <!--/ End Slider Area -->
    <!-- Start Small Banner  -->
    @* <section class="small-banner section">
        <div class="container-fluid">
            <div class="row">
                <!-- Single Banner  -->
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="single-banner">
                        <img src="https://via.placeholder.com/600x370" alt="#">
                        <div class="content">
                            <p>Man's Collectons</p>
                            <h3>Summer travel <br> collection</h3>
                            <a href="#">Discover Now</a>
                        </div>
                    </div>
                </div>
                <!-- /End Single Banner  -->
                <!-- Single Banner  -->
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="single-banner">
                        <img src="https://via.placeholder.com/600x370" alt="#">
                        <div class="content">
                            <p>Bag Collectons</p>
                            <h3>Awesome Bag <br> 2025</h3>
                            <a href="#">Shop Now</a>
                        </div>
                    </div>
                </div>
                <!-- /End Single Banner  -->
                <!-- Single Banner  -->
                <div class="col-lg-4 col-12">
                    <div class="single-banner tab-height">
                        <img src="https://via.placeholder.com/600x370" alt="#">
                        <div class="content">
                            <p>Flash Sale</p>
                            <h3>Mid Season <br> Up to <span>40%</span> Off</h3>
                            <a href="#">Discover Now</a>
                        </div>
                    </div>
                </div>
                <!-- /End Single Banner  -->
            </div>
        </div>
    </section> *@
    <!-- End Small Banner -->
    <!-- Start Product Area -->
    @RenderBody()

    <!-- End Product Area -->
    <!-- Start Shop Services Area -->
    <section class="shop-services section home">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-12">
                    <!-- Start Single Service -->
                    <div class="single-service">
                        <i class="ti-rocket"></i>
                        <h4>Free shiping</h4>
                        <p>Orders over $100</p>
                    </div>
                    <!-- End Single Service -->
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <!-- Start Single Service -->
                    <div class="single-service">
                        <i class="ti-reload"></i>
                        <h4>Free Return</h4>
                        <p>Within 30 days returns</p>
                    </div>
                    <!-- End Single Service -->
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <!-- Start Single Service -->
                    <div class="single-service">
                        <i class="ti-lock"></i>
                        <h4>Sucure Payment</h4>
                        <p>100% secure payment</p>
                    </div>
                    <!-- End Single Service -->
                </div>
                <div class="col-lg-3 col-md-6 col-12">
                    <!-- Start Single Service -->
                    <div class="single-service">
                        <i class="ti-tag"></i>
                        <h4>Best Peice</h4>
                        <p>Guaranteed price</p>
                    </div>
                    <!-- End Single Service -->
                </div>
            </div>
        </div>
    </section>
    <!-- End Shop Services Area -->
    <!-- Start Shop Newsletter  -->
    @await Component.InvokeAsync("Newsletter")
    <!-- End Shop Newsletter -->
    <!-- Start Footer Area -->
    <partial name="_FooterPartial"></partial>
    <!-- /End Footer Area -->
    @*   <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@

    <!-- Jquery -->
    <script src="~/js/layout_General/jquery.min.js"></script>
    <script src="~/js/layout_General/jquery-migrate-3.0.0.js"></script>
    <script src="~/js/layout_General/jquery-ui.min.js"></script>
    <!-- Popper JS -->
    <script src="~/js/layout_General/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="~/js/layout_General/bootstrap.min.js"></script>
    <!-- Color JS -->
    <script src="~/js/layout_General/colors.js"></script>
    <!-- Slicknav JS -->
    <script src="~/js/layout_General/slicknav.min.js"></script>
    <!-- Owl Carousel JS -->
    <script src="~/js/layout_General/owl-carousel.js"></script>
    <!-- Magnific Popup JS -->
    <script src="~/js/layout_General/magnific-popup.js"></script>
    <!-- Waypoints JS -->
    <script src="~/js/layout_General/waypoints.min.js"></script>
    <!-- Countdown JS -->
    <script src="~/js/layout_General/finalcountdown.min.js"></script>
    <!-- Nice Select JS -->
    <script src="~/js/layout_General/nicesellect.js"></script>
    <!-- Flex Slider JS -->
    <script src="~/js/layout_General/flex-slider.js"></script>
    <!-- ScrollUp JS -->
    <script src="~/js/layout_General/scrollup.js"></script>
    <!-- Onepage Nav JS -->
    <script src="~/js/layout_General/onepage-nav.min.js"></script>
    <!-- Easing JS -->
    <script src="~/js/layout_General/easing.js"></script>
    <!-- Active JS -->
    <script src="~/js/layout_General/active.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/MyMvcNetCore.Web/Views/Shared/_MenuAreaPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using MyMvcNetCore.Entities.Identity

@inject SignInManager<ApplicationUser > SignInManager
@inject UserManager<ApplicationUser> UserManager


<div class="menu-area">
    <!-- Main Menu -->
    <nav class="navbar navbar-expand-lg">
        <div class="navbar-collapse">
            <div class="nav-inner">
                <ul class="nav main-menu menu navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Product</a></li>
                    <li><a href="#">Service</a></li>
                    <li>
                        <a href="#">Shop<i class="ti-angle-down"></i><span class="new">New</span></a>
                        <ul class="dropdown">
                            <li><a href="#">Shop Grid</a></li>
                            <li><a href="#">Cart</a></li>
                            <li><a href="#">Checkout</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Pages</a></li>
                    <li>
                        <a href="#">Blog<i class="ti-angle-down"></i></a>
                        <ul class="dropdown">
                            <li><a href="#">Blog Single Sidebar</a></li>
                        </ul>
                    </li>
                    <li><a href="contact.html">Contact Us</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <text>
                        <li>
                            <a href="#">My account<i class="ti-angle-down"></i></a>
                            <ul class="dropdown">

                                <li><a asp-page="/Account/Manage/Index" asp-area="Identity">Profile</a></li>
                                <li><a asp-page="/Account/Manage/ChangePassword" asp-area="Identity">Change password</a></li>
                                <li><a asp-page="/Account/Manage/Email" asp-area="Identity">Manage Email</a></li>

                            </ul>
                        </li>
                        </text>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <!--/ End Main Menu -->
</div>

src/MyMvcNetCore.Web/Views/Shared/_MiddleInnerPartial.cshtml
<div class="middle-inner">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-12">
                <!-- Logo -->
                <div class="logo">
                    <a href="index.html"><img src="images/logo.png" alt="logo"></a>
                </div>
                <!--/ End Logo -->
                <!-- Search Form -->
                <div class="search-top">
                    <div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
                    <!-- Search Form -->
                    <div class="search-top">
                        <form class="search-form">
                            <input type="text" placeholder="Search here..." name="search">
                            <button value="search" type="submit"><i class="ti-search"></i></button>
                        </form>
                    </div>
                    <!--/ End Search Form -->
                </div>
                <!--/ End Search Form -->
                <div class="mobile-nav"></div>
            </div>
            

            <div class="col-lg-8 col-md-7 col-12">
                @* <vc:SearchCustum></vc:SearchCustum> *@
                @await Component.InvokeAsync("SearchProduct")
            </div>
            

            <div class="col-lg-2 col-md-3 col-12">
                <div class="right-bar">
                    <!-- Search Form -->
                    <div class="sinlge-bar">
                        <a href="#" class="single-icon"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                    </div>
                    <div class="sinlge-bar">
                        <a href="#" class="single-icon"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>
                    </div>
                    <div class="sinlge-bar shopping">
                        <a href="#" class="single-icon"><i class="ti-bag"></i> <span class="total-count">2</span></a>
                        <!-- Shopping Item -->
                        <div class="shopping-item">
                            <div class="dropdown-cart-header">
                                <span>2 Items</span>
                                <a href="#">View Cart</a>
                            </div>
                            <ul class="shopping-list">
                                <li>
                                    <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                    <a class="cart-img" href="#"><img src="https://via.placeholder.com/70x70" alt="#"></a>
                                    <h4><a href="#">Samsung Galaxy S23 Ultra</a></h4>
                                    <p class="quantity">1x - <span class="amount">$1200.00</span></p>
                                </li>
                                <li>
                                    <a href="#" class="remove" title="Remove this item"><i class="fa fa-remove"></i></a>
                                    <a class="cart-img" href="#"><img src="https://via.placeholder.com/70x70" alt="#"></a>
                                    <h4><a href="#">Sony WH-1000XM5</a></h4>
                                    <p class="quantity">1x - <span class="amount">$350.00</span></p>
                                </li>
                            </ul>
                            <div class="bottom">
                                <div class="total">
                                    <span>Total</span>
                                    <span class="total-amount">$1550.00</span>
                                </div>
                                <a href="checkout.html" class="btn animate">Checkout</a>
                            </div>
                        </div>
                        <!--/ End Shopping Item -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/MyMvcNetCore.Web/Views/Shared/_TopbarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@using MyMvcNetCore.Commen
@using MyMvcNetCore.Entities.Identity

@inject SignInManager<ApplicationUser > SignInManager
@inject UserManager<ApplicationUser> UserManager



<div class="topbar">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-12">
                <!-- Top Left -->
                <div class="top-left">
                    <ul class="list-main">
                        <li><i class="ti-headphone-alt"></i> +49 801</li>
                        <li><i class="ti-email"></i> support@your_compony.com</li>
                    </ul>
                </div>
                <!--/ End Top Left -->
            </div>
            <div class="col-lg-8 col-md-12 col-12">
                <!-- Top Right -->
                <div class="right-content">
                    <ul class="list-main">

                        @if (SignInManager.IsSignedIn(User))
                        {
                        @*     <li><i class="ti-location-pin"></i> Store location</li>
                            <li><i class="ti-alarm-clock"></i> <a href="#">Daily deal</a></li>
                            <li><i class="ti-user"></i> <a href="#">My account</a></li> *@
                            <li>
                                @*   <a id="manage"  asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a> *@
                                @if (User.IsInRole(SD.Role_Admin))
                                {
                                    <a id="manage" asp-area="Admin" asp-action="Index" asp-controller="Dashboard" >Hello @UserManager.GetUserName(User)!</a>

                                }else if (User.IsInRole(SD.Role_Customer ))
                                {
                                    <a id="manage" asp-area="Customer" asp-action="Index" asp-controller="Dashboard" >Hello @UserManager.GetUserName(User)!</a>

                                }
                                else if (User.IsInRole(SD.Role_Employee ))
                                {


                                }
                                else if (User.IsInRole(SD.Role_Company ))
                                {


                                }


                            </li>
                            <li><i class="ti-power-off"></i><a asp-page="/Account/logout" asp-area="Identity" asp-route-returnUrl="@Context.Request.Path" >Logout</a></li>
                        }
                        else
                        {

                            <li><i class="ti-user"></i><a asp-page="/Account/Register" asp-area="Identity">Register</a></li>
                            <li><i class="ti-lock"></i><a asp-page="/Account/login" asp-area="Identity">Login</a></li>
                        }

                    </ul>
                </div>
                <!-- End Top Right -->
            </div>
        </div>
    </div>
</div>